event:
  # 663BCE: -663
  993AD: 993
  5259BCE: -5259
  # 7176BCE: -7176
  775AD-early: 775
  775AD-late-N: 775
  # 5410BCE: -5410

event_label:
  663BCE: 663BCE
  993AD: 993CE
  5259BCE: 5259BCE
  7176BCE: 7176BCE
  775AD-early: 775CE Early-Rise
  775AD-late-N: 775CE Late-Rise
  5410BCE: 5410BCE

averages:
  775AD-early-S: 775
  775AD-early-N: 775
  993AD-S: 993
  993AD-N: 993

hemisphere:
  663BCE: north
  993AD: north
  993AD-N: north
  993AD-S: south
  5259BCE: north
  7176BCE: north
  775AD-early: north
  775AD-early-N: north
  775AD-late-N: north
  775AD-early-S: south
  5410BCE: north

cbm_model:
  # Miyake17: Miyake17
  Guttler14: Guttler14
  Buntgen18: Buntgen18
  Brehm21: Brehm21

cbm_label:
  G端ttler et al, 2015: G端ttler et al, 2015
  B端ntgen et al, 2018: B端ntgen et al, 2018
  Brehm et al, 2021: Brehm et al, 2021

N_event:
  660BCE: -660
  5259BCE: -5259
  7176BCE: -7176
  5410BCE: -5410

NS_event:
  775AD: 775
  993AD: 993
